import xarray as xr
import numpy as np
from dask.distributed import Client

# CONFIGURATION
MODEL_NAME = "MPI-ESM1-2-HR"
BASE_PATH = "gs://clim_data_reg_useast1/cmip6_downscaled_woodwell/daily/"


def reconstruct():
    print(f"Reconstructing tasmin and tasmax for {MODEL_NAME}...")

    # Load debiased Zarrs (0.1 degree)
    # We assume these have been generated by running global_bias_adjustment.py
    # for each of the three variables.
    path_tas = f"{BASE_PATH}tas/tas_{MODEL_NAME}_ww-isimip_ssp585_day.zarr"
    path_range = f"{BASE_PATH}tasrange/tasrange_{MODEL_NAME}_ww-isimip_ssp585_day.zarr"
    path_skew = f"{BASE_PATH}tasskew/tasskew_{MODEL_NAME}_ww-isimip_ssp585_day.zarr"

    print("Opening debiased datasets...")
    # Open without chunks="auto" to preserve existing disk chunking
    ds_tas = xr.open_zarr(path_tas)
    ds_range = xr.open_zarr(path_range)
    ds_skew = xr.open_zarr(path_skew)

    da_tas = ds_tas["tas"]
    da_range = ds_range["tasrange"]
    da_skew = ds_skew["tasskew"]

    # # FORCE UNIFORM CHUNKING
    # # The source data has 120/121 mixed chunks. We rechunk to a uniform 200x200
    # # to satisfy Zarr's "final chunk must be <= first chunk" rule.
    # target_chunks = {"time": 1000, "latitude": 200, "longitude": 200}
    # da_tas = da_tas.chunk(target_chunks)
    # da_range = da_range.chunk(target_chunks)
    # da_skew = da_skew.chunk(target_chunks)

    print("Reconstructing tasmin...")
    # Formula: min = mean - (skew * range)
    da_min = (da_tas - (da_skew * da_range)).astype("float32")
    ds_min = da_min.to_dataset(name="tasmin")
    ds_min = ds_min.assign_coords(ds_tas.coords)

    for var in ds_min.variables:
        ds_min[var].encoding.pop("chunks", None)

    print("Reconstructing tasmax...")
    # Formula: max = min + range
    da_max = (da_min + da_range).astype("float32")
    ds_max = da_max.to_dataset(name="tasmax")
    ds_max = ds_max.assign_coords(ds_tas.coords)

    for var in ds_max.variables:
        ds_max[var].encoding.pop("chunks", None)

    # Output paths
    path_min_out = f"{BASE_PATH}tasmin/tasmin_{MODEL_NAME}_ww-isimip_ssp585_day.zarr"
    path_max_out = f"{BASE_PATH}tasmax/tasmax_{MODEL_NAME}_ww-isimip_ssp585_day.zarr"

    print(f"Saving tasmin to {path_min_out}...")
    ds_min.to_zarr(path_min_out, mode="w")

    print(f"Saving tasmax to {path_max_out}...")
    ds_max.to_zarr(path_max_out, mode="w")

    print("Done.")


if __name__ == "__main__":
    client = Client()
    reconstruct()
